apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: messager-team
spec:
  template:
    spec:
      $patch: replace
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: role
                    operator: In
                    values:
                      - app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-service
  namespace: messager-team
spec:
  template:
    spec:
      $patch: replace
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: role
                    operator: In
                    values:
                      - app
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: disk
                    operator: In
                    values:
                      - fast
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff
  namespace: messager-team
spec:
  template:
    spec:
      $patch: replace
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: role
                    operator: In
                    values:
                      - app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: messager-team
spec:
  template:
    spec:
      $patch: replace
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: role
                    operator: In
                    values:
                      - app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: messager-team
spec:
  template:
    spec:
      $patch: replace
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: role
                    operator: In
                    values:
                      - system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: messager-team
spec:
  template:
    spec:
      $patch: replace
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: role
                    operator: In
                    values:
                      - system