apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: messager-team
spec:
  template:
    spec:
      containers:
        - name: user-service
          resources:
            requests:
              cpu: "300m"
              memory: "512Mi"
            limits:
              cpu: "600m"
              memory: "1Gi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-service
  namespace: messager-team
spec:
  template:
    spec:
      containers:
        - name: message-service
          resources:
            requests:
              cpu: "300m"
              memory: "512Mi"
            limits:
              cpu: "600m"
              memory: "1Gi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff
  namespace: messager-team
spec:
  template:
    spec:
      containers:
        - name: bff
          resources:
            requests:
              cpu: "250m"
              memory: "384Mi"
            limits:
              cpu: "500m"
              memory: "768Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: messager-team
spec:
  template:
    spec:
      containers:
        - name: frontend
          resources:
            requests:
              cpu: "150m"
              memory: "256Mi"
            limits:
              cpu: "300m"
              memory: "512Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: messager-team
spec:
  template:
    spec:
      containers:
        - name: postgres
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "1000m"
              memory: "2Gi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: messager-team
spec:
  template:
    spec:
      containers:
        - name: minio
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"