apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: messager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Vladislave008/k8s-lab
    targetRevision: main
    path: k8s/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: messager-team
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true