apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: messager-team
resources:
  - s3-pv.yaml
  - create-bucket-job.yaml
  - namespace.yaml
  - configmap.yaml
  - postgres-pvc.yaml
  - minio-pvc.yaml
  - message-uploads-pvc.yaml
  - postgres-deployment.yaml
  - minio-deployment.yaml
  - ingress.yaml
  - user-service-deployment.yaml
  - message-service-deployment.yaml
  - bff-deployment.yaml
  - frontend-deployment.yaml 