apiVersion: v1
kind: PersistentVolume
metadata:
  name: s3-pv-final
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  storageClassName: ""
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  claimRef:
    namespace: messager-team
    name: message-uploads-pvc
  csi:
    driver: ru.yandex.s3.csi
    volumeHandle: "messager-uploads/"
    controllerPublishSecretRef:
      name: csi-s3-secret
      namespace: kube-system
    nodePublishSecretRef:
      name: csi-s3-secret
      namespace: kube-system
    nodeStageSecretRef:
      name: csi-s3-secret
      namespace: kube-system
    volumeAttributes:
      mounter: rclone
      options: ""
  mountOptions:
    - --allow-other