apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: patches/resources.yaml
    target:
      kind: Deployment
      name: .*
  - path: patches/affinity.yaml
    target:
      kind: Deployment
      name: .*
  - path: patches/storage.yaml
    target:
      kind: PersistentVolumeClaim
      name: .*
  - path: patches/ingress-host.yaml
    target:
      kind: Ingress
      name: .*

replicas:
  - name: user-service
    count: 1
  - name: message-service
    count: 1
  - name: bff
    count: 1
  - name: frontend
    count: 1

images:
  - name: mablinov2704/user-service
    newTag: latest
  - name: mablinov2704/message-service
    newTag: latest
  - name: mablinov2704/bff
    newTag: latest
  - name: mablinov2704/frontend
    newTag: latest